study_prefix = "suicide_los"

[file_config]
file_names = [
    "define_study_period.sql",
    "define_age.sql",
    "define_dx_attempt.sql",
    "define_dx_attempt_snomed.sql",
    "define_dx_ideation.sql",
    "define_dx_self_harm.sql",
    "define_dx.sql",
    "define_waiting.sql",
    "table_study_period.sql",
    "table_dx.sql",
    "table_prevalence.sql",
    "table_comorbidity.sql",
    "version.sql",
    "counts.py"
]

[export_config]
count_list = [
    "suicide_los__count_dx_week",
    "suicide_los__count_dx_month",
    "suicide_los__count_study_period_week",
    "suicide_los__count_study_period_month",
    "suicide_los__count_prevalence_demographics",
    "suicide_los__count_prevalence_icd10_month",
    "suicide_los__meta_version",    
]
