create or replace view suicide_los__define_dx_attempt_snomed as select * from (values
('http://snomed.info/sct', '219125007', 'Suicide and selfinflicted poisoning by gases in domestic use (disorder)')
,('http://snomed.info/sct', '219126008', 'Suicide and selfinflicted poisoning by gas distributed by pipeline (disorder)')
,('http://snomed.info/sct', '219127004', 'Suicide and selfinflicted poisoning by liquefied petroleum gas distributed in mobile containers (disorder)')
,('http://snomed.info/sct', '23546003', 'Suicide while incarcerated (event)')
,('http://snomed.info/sct', '274228002', 'Drug overdose - suicide (event)')
,('http://snomed.info/sct', '287188006', 'Suicide - domestic gas (event)')
,('http://snomed.info/sct', '287189003', 'Suicide - car exhaust (event)')
,('http://snomed.info/sct', '287190007', 'Suicide - hanging (event)')
,('http://snomed.info/sct', '287191006', 'Suicide - suffocation (event)')
,('http://snomed.info/sct', '287192004', 'Suicide - drowning (event)')
,('http://snomed.info/sct', '287193009', 'Suicide - firearms (event)')
,('http://snomed.info/sct', '287194003', 'Suicide - cut/stab (event)')
,('http://snomed.info/sct', '287195002', 'Suicide - jumping from a high place (event)')
,('http://snomed.info/sct', '44301001', 'Suicide (event)')
,('http://snomed.info/sct', '51709005', 'Assisted suicide (event)')
,('http://snomed.info/sct', '78070009', 'Suicide by multiple means (event)')
,('http://snomed.info/sct', '891003', 'Suicide by self-administered drug (event)')
) AS t (system, code, display) ;